# builds the content of https://github.com/rectorphp/rector-prefixed
# inspiration from https://github.com/phpstan/phpstan-src/blob/master/.github/workflows/phar.yml
name: Packages Tests

on:
    pull_request: null
    push:
        branches:
            - main

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    packages_tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                package_name:
                    - rector-nette
                    - rector-symfony
                    - rector-laravel
                    - rector-phpunit
                    - rector-cakephp
                    - rector-doctrine

        steps:
            -
                uses: "actions/checkout@v3"
                with:
                    repository: rectorphp/${{ matrix.package_name }}

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -
                run: composer install --ansi

            -
                run: vendor/bin/phpunit
